// Applies a brand folder to the project before a build.
//
//   dart run tool/apply_brand.dart <brand> [--no-icons]
//
// Reads brands/<brand>/brand.json and:
//   1. copies logo/icon/icon_foreground/splash PNGs into assets/branding/
//   2. writes android/brand.properties (applicationId, appName, keyPropertiesFile)
//      which android/app/build.gradle.kts reads
//   3. generates android/app/src/main/res/xml/network_security_config.xml from
//      CLEARTEXT_HOSTS (empty = HTTPS only)
//   4. writes tool/generated/icons.yaml + splash.yaml and runs
//      flutter_launcher_icons and flutter_native_splash (skip with --no-icons)
//   5. sets CFBundleDisplayName in ios/Runner/Info.plist and prints the ATS
//      snippet for the brand's cleartext hosts
//
// No Dart source is touched: the brand values reach the app through
// --dart-define-from-file=brands/<brand>/brand.json at build time (tool/build_brand.sh).
import 'dart:convert';
import 'dart:io';

const requiredKeys = [
  'BRAND_KEY', 'APP_NAME', 'APPLICATION_ID', 'API_BASE_URL_DEV', 'API_BASE_URL_PROD', //
  'PRIMARY_COLOR', 'ACCENT_COLOR', 'BACKGROUND_COLOR', 'SURFACE_COLOR', //
  'PRIVACY_URL', 'TERMS_URL', 'DELETE_ACCOUNT_URL',
];
const images = ['logo.png', 'icon.png', 'icon_foreground.png', 'splash.png'];

void main(List<String> args) async {
  if (args.isEmpty) {
    stderr.writeln('usage: dart run tool/apply_brand.dart <brand> [--no-icons]');
    exit(2);
  }
  final brand = args.first;
  final noIcons = args.contains('--no-icons');
  final root = _projectRoot();
  final dir = Directory('$root/brands/$brand');
  if (!dir.existsSync()) _fail('brand folder not found: ${dir.path}');
  final jsonFile = File('${dir.path}/brand.json');
  if (!jsonFile.existsSync()) _fail('missing ${jsonFile.path}');
  final cfg = (jsonDecode(jsonFile.readAsStringSync()) as Map).map((k, v) => MapEntry(k.toString(), v.toString()));
  for (final k in requiredKeys) {
    if ((cfg[k] ?? '').trim().isEmpty) _fail('brand.json is missing "$k"');
  }
  final appId = cfg['APPLICATION_ID']!.trim();
  if (!RegExp(r'^[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)+$').hasMatch(appId)) {
    _fail('APPLICATION_ID "$appId" is not a valid Android application id');
  }
  final appName = cfg['APP_NAME']!.trim();
  final hosts = _hosts(cfg['CLEARTEXT_HOSTS'] ?? '');

  // 1. images
  final branding = Directory('$root/assets/branding')..createSync(recursive: true);
  for (final img in images) {
    final src = File('${dir.path}/$img');
    if (!src.existsSync()) _fail('missing ${src.path}');
    src.copySync('${branding.path}/$img');
  }
  stdout.writeln('✓ assets/branding/ ← brands/$brand/');

  // 2. android/brand.properties
  final keyProps = File('${dir.path}/key.properties');
  final props = StringBuffer()
    ..writeln('# Generated by tool/apply_brand.dart — do not edit, do not commit.')
    ..writeln('brand=$brand')
    ..writeln('applicationId=$appId')
    ..writeln('appName=${appName.replaceAll('=', '\\=')}')
    ..writeln('keyPropertiesFile=${keyProps.existsSync() ? keyProps.absolute.path : ''}');
  File('$root/android/brand.properties').writeAsStringSync(props.toString());
  stdout.writeln('✓ android/brand.properties (applicationId=$appId, signing=${keyProps.existsSync() ? 'brand keystore' : 'debug key — no brands/$brand/key.properties'})');

  // 3. network security config
  final nsc = StringBuffer()
    ..writeln('<?xml version="1.0" encoding="utf-8"?>')
    ..writeln('<!-- Generated by tool/apply_brand.dart for brand "$brand" from CLEARTEXT_HOSTS. Do not edit by hand. -->')
    ..writeln('<network-security-config>')
    ..writeln('    <base-config cleartextTrafficPermitted="false">')
    ..writeln('        <trust-anchors><certificates src="system" /></trust-anchors>')
    ..writeln('    </base-config>');
  if (hosts.isNotEmpty) {
    nsc.writeln('    <!-- Plain http:// streams are allowed ONLY for these hosts. Any other http host fails to play. -->');
    nsc.writeln('    <domain-config cleartextTrafficPermitted="true">');
    for (final h in hosts) {
      nsc.writeln('        <domain includeSubdomains="true">$h</domain>');
    }
    nsc.writeln('    </domain-config>');
  }
  nsc.writeln('</network-security-config>');
  final nscFile = File('$root/android/app/src/main/res/xml/network_security_config.xml')..parent.createSync(recursive: true);
  nscFile.writeAsStringSync(nsc.toString());
  stdout.writeln('✓ network_security_config.xml (${hosts.isEmpty ? 'HTTPS only' : 'cleartext for: ${hosts.join(', ')}'})');

  // 4. icons + splash
  final gen = Directory('$root/tool/generated')..createSync(recursive: true);
  final bg = _hex(cfg['BACKGROUND_COLOR']!);
  File('${gen.path}/icons.yaml').writeAsStringSync('''
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/branding/icon.png"
  adaptive_icon_background: "$bg"
  adaptive_icon_foreground: "assets/branding/icon_foreground.png"
''');
  File('${gen.path}/splash.yaml').writeAsStringSync('''
flutter_native_splash:
  color: "$bg"
  image: assets/branding/splash.png
  android_12:
    color: "$bg"
    image: assets/branding/splash.png
''');
  if (!noIcons) {
    await _run(root, ['dart', 'run', 'flutter_launcher_icons', '-f', 'tool/generated/icons.yaml']);
    await _run(root, ['dart', 'run', 'flutter_native_splash:create', '--path=tool/generated/splash.yaml']);
    stdout.writeln('✓ launcher icons and splash regenerated');
  } else {
    stdout.writeln('· icons/splash skipped (--no-icons)');
  }

  // 5. iOS display name + ATS hint
  final plist = File('$root/ios/Runner/Info.plist');
  if (plist.existsSync()) {
    var text = plist.readAsStringSync();
    text = text.replaceFirstMapped(
      RegExp(r'(<key>CFBundleDisplayName</key>\s*<string>)[^<]*(</string>)'),
      (m) => '${m.group(1)}${_xml(appName)}${m.group(2)}',
    );
    plist.writeAsStringSync(text);
    stdout.writeln('✓ ios/Runner/Info.plist CFBundleDisplayName = "$appName" (bundle id is set in Xcode: $appId)');
  }
  if (hosts.isNotEmpty) {
    stdout.writeln('\niOS ATS: add to ios/Runner/Info.plist (http hosts not listed will fail to play):');
    stdout.writeln('  <key>NSAppTransportSecurity</key><dict><key>NSExceptionDomains</key><dict>');
    for (final h in hosts) {
      stdout.writeln('    <key>$h</key><dict><key>NSExceptionAllowsInsecureHTTPLoads</key><true/><key>NSIncludesSubdomains</key><true/></dict>');
    }
    stdout.writeln('  </dict></dict>');
  }
  stdout.writeln('\nBrand "$brand" applied. Build with:\n  ./tool/build_brand.sh $brand apk prod');
}

String _projectRoot() {
  var d = Directory.current;
  while (!File('${d.path}/pubspec.yaml').existsSync()) {
    if (d.parent.path == d.path) _fail('run from the app/ folder');
    d = d.parent;
  }
  return d.path;
}

List<String> _hosts(String raw) => raw.split(RegExp(r'[,\s]+')).map((h) => h.trim().toLowerCase()).where((h) => h.isNotEmpty).toSet().toList();

String _hex(String v) {
  var h = v.trim().replaceFirst('#', '');
  if (h.length == 8) h = h.substring(2);
  if (h.length != 6 || int.tryParse(h, radix: 16) == null) _fail('bad colour "$v" (use #RRGGBB)');
  return '#${h.toUpperCase()}';
}

String _xml(String s) => s.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');

Future<void> _run(String root, List<String> cmd) async {
  stdout.writeln('→ ${cmd.join(' ')}');
  final p = await Process.start(cmd.first, cmd.sublist(1), workingDirectory: root, mode: ProcessStartMode.inheritStdio);
  final code = await p.exitCode;
  if (code != 0) _fail('command failed (${cmd.join(' ')})');
}

Never _fail(String msg) {
  stderr.writeln('apply_brand: $msg');
  exit(1);
}
