#!/usr/bin/env bash
# Build the app for one brand.
#
#   ./tool/build_brand.sh <brand> <apk|appbundle|run> [dev|prod] [--debug] [--no-icons]
#
# Examples:
#   ./tool/build_brand.sh caritv apk dev --debug        # debug APK, dev flavour
#   ./tool/build_brand.sh islandtv appbundle prod       # release AAB for Play (needs brands/islandtv/key.properties)
#   ./tool/build_brand.sh islandtv run dev              # run on a connected device
#
# The brand's values reach Dart via --dart-define-from-file; Android id/name/
# signing/cleartext policy come from files generated by tool/apply_brand.dart.
set -euo pipefail
cd "$(dirname "$0")/.."

BRAND="${1:-}"; TARGET="${2:-apk}"; ENV="${3:-prod}"
MODE="--release"; EXTRA=()
for a in "${@:4}"; do
  case "$a" in
    --debug) MODE="--debug" ;;
    --profile) MODE="--profile" ;;
    --no-icons) EXTRA+=("--no-icons") ;;
    *) echo "unknown option: $a" >&2; exit 2 ;;
  esac
done
[[ -z "$BRAND" ]] && { echo "usage: $0 <brand> <apk|appbundle|run> [dev|prod] [--debug] [--no-icons]" >&2; exit 2; }
[[ -f "brands/$BRAND/brand.json" ]] || { echo "no such brand: brands/$BRAND/brand.json" >&2; exit 1; }
[[ "$ENV" == "dev" || "$ENV" == "prod" ]] || { echo "env must be dev or prod" >&2; exit 2; }

dart run tool/apply_brand.dart "$BRAND" "${EXTRA[@]}"

DEFINES="--dart-define-from-file=brands/$BRAND/brand.json"
ENTRY="lib/main_$ENV.dart"
case "$TARGET" in
  apk)       flutter build apk       $MODE --flavor "$ENV" -t "$ENTRY" $DEFINES ;;
  appbundle) flutter build appbundle $MODE --flavor "$ENV" -t "$ENTRY" $DEFINES ;;
  run)       flutter run             $MODE --flavor "$ENV" -t "$ENTRY" $DEFINES ;;
  *) echo "target must be apk, appbundle or run" >&2; exit 2 ;;
esac

if [[ "$TARGET" == "apk" ]]; then
  echo "APK: build/app/outputs/flutter-apk/app-$ENV-${MODE#--}.apk"
elif [[ "$TARGET" == "appbundle" ]]; then
  echo "AAB: build/app/outputs/bundle/${ENV}Release/app-$ENV-release.aab"
fi
